Repository opendevstack/opendevstack.github.io, pull requests merged in 2018-11, with the labels that each got.

#53 Corrected the release date
  index.html
Labels: bug

#54 add link to v1 board
  index.html
Labels: enhancement

#59 Write development and update guide
  doc/development-guide.md
  doc/update-guide.md
Labels: documentation

#61 Linked development and update guide
  doc/development-guide.md
  doc/update-guide.md
  index.html
Labels: documentation
